#!/bin/bash
#PBS -N pbs_job
#PBS -q batch
#PBS -l nodes=3:ppn=4
#PBS -l walltime=12:00:00
#PBS -e stderr.log
#PBS -o stdout.log
#PBS -V

cd $PBS_O_WORKDIR

START=$(date +%s.%N)

mpiexec -np 12 python pix2sky.py data/in.fits data/in_xy.cat --quiet

END=$(date +%s.%N)

DIFF=$(echo "$END - $START" | bc)

echo 'Execution time: ' $DIFF
